name: Publish to npm
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  handle-contributors-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4
      
      # Step 2: Add contributor (native implementation)
      - name: Update contributors
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          # Install jq for JSON processing
          sudo apt-get install -y jq
          
          # Get contributor's GitHub username
          CONTRIBUTOR="@${{ github.event.pull_request.user.login }}"
          
          # Update package.json
          if [ -f package.json ]; then
            # Read current contributors or initialize array
            CURRENT_CONTRIBUTORS=$(jq '.contributors // []' package.json)
            
            # Add new contributor if not already present
            UPDATED_CONTRIBUTORS=$(echo "$CURRENT_CONTRIBUTORS" | jq --arg user "$CONTRIBUTOR" '. + [$user] | unique')
            
            # Write back to package.json
            jq --argjson contributors "$UPDATED_CONTRIBUTORS" '.contributors = $contributors' package.json > temp.json
            mv temp.json package.json
            
            echo "Added contributor: $CONTRIBUTOR"
          else
            echo "package.json not found"
            exit 1
          fi

      # Step 3: Commit changes
      - name: Commit contributor updates
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git commit -m "docs: Add @${{ github.event.pull_request.user.login }} as contributor" || echo "No changes to commit"
          git push

      # Step 4: Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      # Step 5: Install dependencies
      - run: npm ci

      # Step 6: Run tests (optional)
      - run: npm test

      # Step 7: Publish to npm
      - name: Publish to npm
        if: |
          github.event_name == 'push' || 
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          npm version patch -m "Auto-bump: ${{ github.event.head_commit.message || 'Add contributor' }}"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.patternidgenerator }}