name: Publish to npm
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  handle-contributors-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Configure Git identity (CRITICAL FIX)
      - name: Set up Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # Step 3: Add contributor (native implementation)
      - name: Update contributors
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          sudo apt-get install -y jq
          CONTRIBUTOR="@${{ github.event.pull_request.user.login }}"
          CURRENT_CONTRIBUTORS=$(jq '.contributors // []' package.json)
          UPDATED_CONTRIBUTORS=$(echo "$CURRENT_CONTRIBUTORS" | jq --arg user "$CONTRIBUTOR" '. + [$user] | unique')
          jq --argjson contributors "$UPDATED_CONTRIBUTORS" '.contributors = $contributors' package.json > temp.json
          mv temp.json package.json

      # Step 4: Commit changes
      - name: Commit contributor updates
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: |
          git add package.json
          git commit -m "docs: Add @${{ github.event.pull_request.user.login }} as contributor" || echo "No changes to commit"
          git push

      # Step 5: Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      # Step 6: Install + Test
      - run: npm ci
      - run: npm test

      # Step 7: Publish to npm
      - name: Publish to npm
        if: |
          github.event_name == 'push' || 
          (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          npm version patch -m "Auto-bump: ${{ github.event.head_commit.message || 'Add contributor' }}"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.patternidgenerator }}